# Generated by Django 3.1.2 on 2021-01-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201225_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medium_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
