# Generated by Django 3.2.9 on 2022-02-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
