# Generated by Django 3.1.2 on 2020-10-30 13:18

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_auto_20201029_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 16, 18, 48, 934904)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default='My default movie description', max_length=80),
        ),
    ]
