# Generated by Django 3.2.9 on 2022-03-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_rename_cover_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.CreateModel(
            name='PostSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_post.category')),
            ],
            options={
                'verbose_name': 'Post Serisi',
                'verbose_name_plural': 'Post Serileri',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_post.postseries'),
        ),
    ]
