# Generated by Django 3.1.2 on 2020-10-30 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_auto_20201030_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='post',
            name='estimated_reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 19, 8, 57, 439146)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default='My default movie description', max_length=200),
        ),
    ]
