# Generated by Django 3.1.2 on 2020-10-30 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_auto_20201030_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='static/covers'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 19, 51, 51, 831904)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default='My default movie description', max_length=350),
        ),
    ]
