# Generated by Django 3.1.2 on 2020-10-30 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0006_auto_20201030_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 20, 11, 24, 218282)),
        ),
    ]
