# Generated by Django 3.2.9 on 2022-03-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_alter_post_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postseries',
            options={'ordering': ('name',), 'verbose_name': 'Gönderi Serisi', 'verbose_name_plural': 'Gönderi Serileri'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
