# Generated by Django 3.1.2 on 2020-11-02 14:36

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_auto_20201031_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Film', 'FİLM'), ('Sanat', 'SANAT'), ('Müzik', 'MÜZİK')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 36, 53, 751586)),
        ),
    ]
