# Generated by Django 3.1.2 on 2020-11-02 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0009_auto_20201102_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 37, 24, 836237)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default='Slug is a newspaper term.//\n        A slug is a short label for something, containing only letters,//\n        numbers, underscores or hyphens. They’re generally used in URLs.', max_length=350),
        ),
    ]
