# Generated by Django 3.1.2 on 2020-12-03 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0020_auto_20201203_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='blog_post.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 17, 0, 44, 190360)),
        ),
    ]
