# Generated by Django 3.1.2 on 2020-12-03 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0021_auto_20201203_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('body',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 17, 6, 19, 835756)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default='Will shown at home screen.', max_length=350),
        ),
    ]
