# Generated by Django 3.1.2 on 2020-12-09 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0041_auto_20201204_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 18, 8, 57, 679666)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
