# Generated by Django 3.1.2 on 2021-01-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0044_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='description',
        ),
    ]
