# Generated by Django 3.2.9 on 2022-02-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0046_auto_20220123_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
